In [31]:
import pandas as pd
import numpy as np
import plotly.express as px
import streamlit as st
import pymongo
import streamlit as st

In [32]:
client= pymongo.MongoClient("mongodb://localhost:27017")

db= client["Airbnb"]
collection= db["rooms"]

Property details

In [33]:
data= []

for i in collection.find({},{"_id":1, 
                             "listing_url":1, 
                             "name":1, 'property_type':1, 'room_type':1, 
                             'bed_type':1, 'minimum_nights':1, 'maximum_nights':1, 
                             'cancellation_policy':1, 'accommodates':1, 'bedrooms':1, 
                             'beds':1, 'number_of_reviews':1, 'bathrooms':1, 
                             'price':1, 'extra_people':1, 'guests_included':1, 
                             'images.picture_url':1, 'review_scores':1,'cleaning_fee':1,
                             'review_scores':1}):
    data.append(i)

In [34]:
df_viz= pd.DataFrame(data)
df_viz

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,cleaning_fee,extra_people,guests_included,images,review_scores
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,1.0,1.0,70,1.0,135,135.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,Bed and breakfast,Private room,Real Bed,1,1125,moderate,3,1.0,2.0,29,1.0,121,NaN,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 9, 'review_scores_c..."
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1.0,2.0,3,1.0,699,NaN,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,Guesthouse,Private room,Futon,1,500,strict_14_with_grace_period,1,1.0,1.0,81,1.0,181,50.0,100,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,Apartment,Entire home/apt,Real Bed,10,21,strict_14_with_grace_period,2,0.0,1.0,64,1.0,181,50.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1,1125,flexible,2,2.0,3.0,0,1.0,501,NaN,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{}
5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,2.0,4.0,15,2.0,220,315.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Apartment,Private room,Real Bed,3,1125,flexible,1,1.0,1.0,4,1.0,400,NaN,300,2,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,Apartment,Private room,Real Bed,3,1125,moderate,2,1.0,1.0,0,1.0,60,50.0,50,2,{'picture_url': 'https://a0.muscache.com/im/pi...,{}
5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartment,Entire home/apt,Real Bed,1,1125,flexible,6,1.0,2.0,0,2.0,750,NaN,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{}

In [5]:
df_viz.describe()

,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,cleaning_fee,extra_people,guests_included
count,5555.000000,5550.000000,5542.000000,5555.000000,5545.000000,5555.000000,4024.000000,5555.000000,5555.000000
mean,3.505851,1.411712,2.071454,27.606481,1.291163,278.766157,94.074801,22.791899,1.747435
std,2.297019,1.041942,1.619660,49.798376,0.702265,842.215531,110.203782,69.331511,1.487352
min,1.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,0.000000,1.000000
25%,2.000000,1.000000,1.000000,1.000000,1.000000,70.000000,23.000000,0.000000,1.000000
50%,3.000000,1.000000,2.000000,5.000000,1.000000,129.000000,60.000000,0.000000,1.000000
75%,4.000000,2.000000,3.000000,32.000000,1.000000,280.000000,129.000000,20.000000,2.000000
max,16.000000,20.000000,25.000000,533.000000,16.000000,48842.000000,2000.000000,2346.000000,16.000000

In [6]:
df_viz.isnull().sum()

_id                       0
listing_url               0
name                      0
property_type             0
room_type                 0
bed_type                  0
minimum_nights            0
maximum_nights            0
cancellation_policy       0
accommodates              0
bedrooms                  5
beds                     13
number_of_reviews         0
bathrooms                10
price                     0
cleaning_fee           1531
extra_people              0
guests_included           0
images                    0
review_scores             0
dtype: int64

Handling Null values (NaN)

In [7]:
df_viz.fillna(0, inplace=True)
df_viz

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,cleaning_fee,extra_people,guests_included,images,review_scores
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,1.0,1.0,70,1.0,135,135.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,Bed and breakfast,Private room,Real Bed,1,1125,moderate,3,1.0,2.0,29,1.0,121,0.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 9, 'review_scores_c..."
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1.0,2.0,3,1.0,699,0.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,Guesthouse,Private room,Futon,1,500,strict_14_with_grace_period,1,1.0,1.0,81,1.0,181,50.0,100,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,Apartment,Entire home/apt,Real Bed,10,21,strict_14_with_grace_period,2,0.0,1.0,64,1.0,181,50.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1,1125,flexible,2,2.0,3.0,0,1.0,501,0.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{}
5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,2.0,4.0,15,2.0,220,315.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Apartment,Private room,Real Bed,3,1125,flexible,1,1.0,1.0,4,1.0,400,0.0,300,2,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,Apartment,Private room,Real Bed,3,1125,moderate,2,1.0,1.0,0,1.0,60,50.0,50,2,{'picture_url': 'https://a0.muscache.com/im/pi...,{}
5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartment,Entire home/apt,Real Bed,1,1125,flexible,6,1.0,2.0,0,2.0,750,0.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{}

In [8]:
df_viz.head(5
            )

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,cleaning_fee,extra_people,guests_included,images,review_scores
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,1.0,1.0,70,1.0,135,135.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,Bed and breakfast,Private room,Real Bed,1,1125,moderate,3,1.0,2.0,29,1.0,121,0.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 9, 'review_scores_c..."
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1.0,2.0,3,1.0,699,0.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,Guesthouse,Private room,Futon,1,500,strict_14_with_grace_period,1,1.0,1.0,81,1.0,181,50.0,100,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,Apartment,Entire home/apt,Real Bed,10,21,strict_14_with_grace_period,2,0.0,1.0,64,1.0,181,50.0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."

In [9]:
df_viz.dtypes

_id                     object
listing_url             object
name                    object
property_type           object
room_type               object
bed_type                object
minimum_nights          object
maximum_nights          object
cancellation_policy     object
accommodates             int64
bedrooms               float64
beds                   float64
number_of_reviews        int64
bathrooms              float64
price                    int64
cleaning_fee           float64
extra_people             int64
guests_included          int64
images                  object
review_scores           object
dtype: object

Typecast

In [10]:
df_viz["minimum_nights"]= df_viz["minimum_nights"].astype(int)
df_viz["maximum_nights"]= df_viz["maximum_nights"].astype(int)
df_viz["bedrooms"]= df_viz["bedrooms"].astype(int)
df_viz["beds"]= df_viz["beds"].astype(int)
df_viz["bathrooms"]= df_viz["bathrooms"].astype(str).astype(float).astype(int)
df_viz["price"]= df_viz["price"].astype(str).astype(float).astype(int)
df_viz["extra_people"]= df_viz["extra_people"].astype(str).astype(float).astype(int)
df_viz["guests_included"]= df_viz["guests_included"].astype(str).astype(float).astype(int)
df_viz["cleaning_fee"]= df_viz["cleaning_fee"].astype(str).astype(float).astype(int)

df_viz.dtypes

_id                    object
listing_url            object
name                   object
property_type          object
room_type              object
bed_type               object
minimum_nights          int32
maximum_nights          int32
cancellation_policy    object
accommodates            int64
bedrooms                int32
beds                    int32
number_of_reviews       int64
bathrooms               int32
price                   int32
cleaning_fee            int32
extra_people            int32
guests_included         int32
images                 object
review_scores          object
dtype: object

In [11]:
df_viz # FINAL DATAFRAME

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,cleaning_fee,extra_people,guests_included,images,review_scores
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,1,1,70,1,135,135,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,Bed and breakfast,Private room,Real Bed,1,1125,moderate,3,1,2,29,1,121,0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 9, 'review_scores_c..."
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,1,2,3,1,699,0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,Guesthouse,Private room,Futon,1,500,strict_14_with_grace_period,1,1,1,81,1,181,50,100,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,Apartment,Entire home/apt,Real Bed,10,21,strict_14_with_grace_period,2,0,1,64,1,181,50,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1,1125,flexible,2,2,3,0,1,501,0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{}
5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,2,4,15,2,220,315,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Apartment,Private room,Real Bed,3,1125,flexible,1,1,1,4,1,400,0,300,2,{'picture_url': 'https://a0.muscache.com/im/pi...,"{'review_scores_accuracy': 10, 'review_scores_..."
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,Apartment,Private room,Real Bed,3,1125,moderate,2,1,1,0,1,60,50,50,2,{'picture_url': 'https://a0.muscache.com/im/pi...,{}
5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartment,Entire home/apt,Real Bed,1,1125,flexible,6,1,2,0,2,750,0,0,1,{'picture_url': 'https://a0.muscache.com/im/pi...,{}

HOST DETAILS

In [12]:
#User

host = []

for i in collection.find({},{"_id":1, "host":1}):
    host.append(i)

df_viz_h= pd.DataFrame(host)
df_viz_h

           _id                                               host
0      1003530  {'host_id': '454250', 'host_url': 'https://www...
1     10133554  {'host_id': '52004703', 'host_url': 'https://w...
2     10059872  {'host_id': '51624384', 'host_url': 'https://w...
3     10084023  {'host_id': '51744313', 'host_url': 'https://w...
4     10091713  {'host_id': '13764143', 'host_url': 'https://w...
...        ...                                                ...
5550   9985696  {'host_id': '51303748', 'host_url': 'https://w...
5551   9993190  {'host_id': '51013381', 'host_url': 'https://w...
5552   9887054  {'host_id': '31386255', 'host_url': 'https://w...
5553   9907907  {'host_id': '47615848', 'host_url': 'https://w...
5554   9936016  {'host_id': '47092481', 'host_url': 'https://w...

[5555 rows x 2 columns]

In [13]:
host_columns= {'_id':[],'host_id':[], 'host_url':[], 'host_name':[], 
               'host_location':[],"host_response_time":[], 'host_thumbnail_url':[], 
               'host_picture_url':[], 'host_neighbourhood':[], 'host_response_rate':[], 
               'host_is_superhost':[], 'host_has_profile_pic':[], 'host_identity_verified':[], 
               'host_listings_count':[], 'host_total_listings_count':[], 'host_verifications':[]}

for i in df_viz_h["_id"]:
    host_columns["_id"].append(i)
for i in df_viz_h["host"]:
    host_columns["host_id"].append(i["host_id"])
    host_columns["host_url"].append(i["host_url"])
    host_columns["host_name"].append(i["host_name"])
    host_columns["host_location"].append(i["host_location"])
    host_columns["host_response_time"].append(i.get("host_response_time"))
    host_columns["host_thumbnail_url"].append(i["host_thumbnail_url"])
    host_columns["host_picture_url"].append(i["host_picture_url"])
    host_columns["host_neighbourhood"].append(i["host_neighbourhood"])
    host_columns["host_response_rate"].append(i.get("host_response_rate"))
    host_columns["host_is_superhost"].append(i["host_is_superhost"])
    host_columns["host_has_profile_pic"].append(i["host_has_profile_pic"])
    host_columns["host_identity_verified"].append(i["host_identity_verified"])
    host_columns["host_listings_count"].append(i["host_listings_count"])
    host_columns["host_total_listings_count"].append(i["host_total_listings_count"])
    host_columns["host_verifications"].append(i["host_verifications"])

In [ ]:
host_columns

In [14]:
df_viz_h= pd.DataFrame(host_columns)
df_viz_h

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,1003530,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",within an hour,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,,100.0,True,True,True,3,3,"[email, phone, reviews, jumio, offline_governm..."
1,10133554,52004703,https://www.airbnb.com/users/show/52004703,Mehmet Emin,"Istanbul, İstanbul, Turkey",within a few hours,https://a0.muscache.com/im/pictures/user/4cb6b...,https://a0.muscache.com/im/pictures/user/4cb6b...,,100.0,False,True,True,2,2,"[email, phone, facebook, reviews, jumio, offli..."
2,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",None,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,NaN,False,True,False,1,1,"[email, phone, reviews, jumio, government_id]"
3,10084023,51744313,https://www.airbnb.com/users/show/51744313,Yi,United States,within an hour,https://a0.muscache.com/im/pictures/user/a204d...,https://a0.muscache.com/im/pictures/user/a204d...,Shek Kip Mei,100.0,False,True,True,2,2,"[email, phone, reviews, jumio, offline_governm..."
4,10091713,13764143,https://www.airbnb.com/users/show/13764143,Ben,"New South Wales, Australia",None,https://a0.muscache.com/im/pictures/03c4d82b-7...,https://a0.muscache.com/im/pictures/03c4d82b-7...,Surry Hills,NaN,False,True,True,1,1,"[email, phone, google, reviews, jumio, offline..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",None,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,,NaN,False,True,False,2,2,"[email, phone]"
5551,9993190,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,,99.0,False,True,True,58,58,"[email, phone, reviews, kba, work_email]"
5552,9887054,31386255,https://www.airbnb.com/users/show/31386255,Cat,Hong Kong,within a day,https://a0.muscache.com/im/pictures/965f2c12-5...,https://a0.muscache.com/im/pictures/965f2c12-5...,Causeway Bay,60.0,False,True,False,7,7,"[email, phone, reviews]"
5553,9907907,47615848,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",None,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,,NaN,False,True,False,1,1,"[email, phone]"
5554,9936016,47092481,https://www.airbnb.com/users/show/47092481,Aliane,BR,None,https://a0.muscache.com/im/pictures/4b17fc8e-4...,https://a0.muscache.com/im/pictures/4b17fc8e-4...,,NaN,False,True,False,1,1,[phone]

In [15]:
df_viz_h.isnull().sum()

_id                             0
host_id                         0
host_url                        0
host_name                       0
host_location                   0
host_response_time           1388
host_thumbnail_url              0
host_picture_url                0
host_neighbourhood              0
host_response_rate           1388
host_is_superhost               0
host_has_profile_pic            0
host_identity_verified          0
host_listings_count             0
host_total_listings_count       0
host_verifications              0
dtype: int64

In [15]:
df_viz_h.fillna(0, inplace=True)

In [16]:
df_viz_h.head(5)

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,1003530,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",within an hour,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,,100.0,True,True,True,3,3,"[email, phone, reviews, jumio, offline_governm..."
1,10133554,52004703,https://www.airbnb.com/users/show/52004703,Mehmet Emin,"Istanbul, İstanbul, Turkey",within a few hours,https://a0.muscache.com/im/pictures/user/4cb6b...,https://a0.muscache.com/im/pictures/user/4cb6b...,,100.0,False,True,True,2,2,"[email, phone, facebook, reviews, jumio, offli..."
2,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",0,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,0.0,False,True,False,1,1,"[email, phone, reviews, jumio, government_id]"
3,10084023,51744313,https://www.airbnb.com/users/show/51744313,Yi,United States,within an hour,https://a0.muscache.com/im/pictures/user/a204d...,https://a0.muscache.com/im/pictures/user/a204d...,Shek Kip Mei,100.0,False,True,True,2,2,"[email, phone, reviews, jumio, offline_governm..."
4,10091713,13764143,https://www.airbnb.com/users/show/13764143,Ben,"New South Wales, Australia",0,https://a0.muscache.com/im/pictures/03c4d82b-7...,https://a0.muscache.com/im/pictures/03c4d82b-7...,Surry Hills,0.0,False,True,True,1,1,"[email, phone, google, reviews, jumio, offline..."

In [17]:
df_viz_h.isnull().sum()

_id                          0
host_id                      0
host_url                     0
host_name                    0
host_location                0
host_response_time           0
host_thumbnail_url           0
host_picture_url             0
host_neighbourhood           0
host_response_rate           0
host_is_superhost            0
host_has_profile_pic         0
host_identity_verified       0
host_listings_count          0
host_total_listings_count    0
host_verifications           0
dtype: int64

In [19]:
df_viz_h.dtypes

_id                           object
host_id                       object
host_url                      object
host_name                     object
host_location                 object
host_response_time            object
host_thumbnail_url            object
host_picture_url              object
host_neighbourhood            object
host_response_rate           float64
host_is_superhost               bool
host_has_profile_pic            bool
host_identity_verified          bool
host_listings_count            int64
host_total_listings_count      int64
host_verifications            object
dtype: object

In [20]:
list_index= []
for index,row in df_viz_h.iterrows():
    if row["host_neighbourhood"] =='':
        list_index.append(index)

In [21]:
len(list_index)

1923

In [22]:
df_viz_h["host_response_time"].fillna("Not Specified",inplace= True)
df_viz_h["host_response_rate"].fillna("Not Specified",inplace= True)
df_viz_h["host_neighbourhood"]= df_viz_h["host_neighbourhood"].replace({'':"Not Specified"})

C:\Users\brijesh\AppData\Local\Temp\ipykernel_21368\4263781485.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viz_h["host_response_time"].fillna("Not Specified",inplace= True)
C:\Users\brijesh\AppData\Local\Temp\ipykernel_21368\4263781485.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_viz_h["host_response_rate"].fillna("Not Specified",inplace= True)

In [23]:
df_viz_h.head(5)

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,1003530,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",within an hour,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,Not Specified,100.0,True,True,True,3,3,"[email, phone, reviews, jumio, offline_governm..."
1,10133554,52004703,https://www.airbnb.com/users/show/52004703,Mehmet Emin,"Istanbul, İstanbul, Turkey",within a few hours,https://a0.muscache.com/im/pictures/user/4cb6b...,https://a0.muscache.com/im/pictures/user/4cb6b...,Not Specified,100.0,False,True,True,2,2,"[email, phone, facebook, reviews, jumio, offli..."
2,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",0,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,0.0,False,True,False,1,1,"[email, phone, reviews, jumio, government_id]"
3,10084023,51744313,https://www.airbnb.com/users/show/51744313,Yi,United States,within an hour,https://a0.muscache.com/im/pictures/user/a204d...,https://a0.muscache.com/im/pictures/user/a204d...,Shek Kip Mei,100.0,False,True,True,2,2,"[email, phone, reviews, jumio, offline_governm..."
4,10091713,13764143,https://www.airbnb.com/users/show/13764143,Ben,"New South Wales, Australia",0,https://a0.muscache.com/im/pictures/03c4d82b-7...,https://a0.muscache.com/im/pictures/03c4d82b-7...,Surry Hills,0.0,False,True,True,1,1,"[email, phone, google, reviews, jumio, offline..."

In [24]:
df_viz_h.isnull().sum()

_id                          0
host_id                      0
host_url                     0
host_name                    0
host_location                0
host_response_time           0
host_thumbnail_url           0
host_picture_url             0
host_neighbourhood           0
host_response_rate           0
host_is_superhost            0
host_has_profile_pic         0
host_identity_verified       0
host_listings_count          0
host_total_listings_count    0
host_verifications           0
dtype: int64

In [25]:
df_viz_h["host_is_superhost"]= df_viz_h["host_is_superhost"].map({False: "No", True: "Yes"})
df_viz_h["host_has_profile_pic"]= df_viz_h["host_has_profile_pic"].map({False: "No", True: "Yes"})
df_viz_h["host_identity_verified"]= df_viz_h["host_identity_verified"].map({False: "No", True: "Yes"})
df_viz_h # FINAL DATAFRAME

,_id,host_id,host_url,host_name,host_location,host_response_time,host_thumbnail_url,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,1003530,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",within an hour,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,Not Specified,100.0,Yes,Yes,Yes,3,3,"[email, phone, reviews, jumio, offline_governm..."
1,10133554,52004703,https://www.airbnb.com/users/show/52004703,Mehmet Emin,"Istanbul, İstanbul, Turkey",within a few hours,https://a0.muscache.com/im/pictures/user/4cb6b...,https://a0.muscache.com/im/pictures/user/4cb6b...,Not Specified,100.0,No,Yes,Yes,2,2,"[email, phone, facebook, reviews, jumio, offli..."
2,10059872,51624384,https://www.airbnb.com/users/show/51624384,Giovanni,"Hong Kong, Hong Kong",0,https://a0.muscache.com/im/pictures/264b82a7-7...,https://a0.muscache.com/im/pictures/264b82a7-7...,Soho,0.0,No,Yes,No,1,1,"[email, phone, reviews, jumio, government_id]"
3,10084023,51744313,https://www.airbnb.com/users/show/51744313,Yi,United States,within an hour,https://a0.muscache.com/im/pictures/user/a204d...,https://a0.muscache.com/im/pictures/user/a204d...,Shek Kip Mei,100.0,No,Yes,Yes,2,2,"[email, phone, reviews, jumio, offline_governm..."
4,10091713,13764143,https://www.airbnb.com/users/show/13764143,Ben,"New South Wales, Australia",0,https://a0.muscache.com/im/pictures/03c4d82b-7...,https://a0.muscache.com/im/pictures/03c4d82b-7...,Surry Hills,0.0,No,Yes,Yes,1,1,"[email, phone, google, reviews, jumio, offline..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",0,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,Not Specified,0.0,No,Yes,No,2,2,"[email, phone]"
5551,9993190,51013381,https://www.airbnb.com/users/show/51013381,Coconut Condos,"Lahaina, Hawaii, United States",within an hour,https://a0.muscache.com/im/pictures/fa071e13-8...,https://a0.muscache.com/im/pictures/fa071e13-8...,Not Specified,99.0,No,Yes,Yes,58,58,"[email, phone, reviews, kba, work_email]"
5552,9887054,31386255,https://www.airbnb.com/users/show/31386255,Cat,Hong Kong,within a day,https://a0.muscache.com/im/pictures/965f2c12-5...,https://a0.muscache.com/im/pictures/965f2c12-5...,Causeway Bay,60.0,No,Yes,No,7,7,"[email, phone, reviews]"
5553,9907907,47615848,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",0,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,Not Specified,0.0,No,Yes,No,1,1,"[email, phone]"
5554,9936016,47092481,https://www.airbnb.com/users/show/47092481,Aliane,BR,0,https://a0.muscache.com/im/pictures/4b17fc8e-4...,https://a0.muscache.com/im/pictures/4b17fc8e-4...,Not Specified,0.0,No,Yes,No,1,1,[phone]

Host adress and Neighbourhood details

In [26]:
host_adress=[]
for i in collection.find({},{"_id":1, "address":1}):
    host_adress.append(i)

In [27]:
host_pre= pd.DataFrame(host_adress)

In [29]:
host_pre

           _id                                            address
0      1003530  {'street': 'New York, NY, United States', 'sub...
1     10133554  {'street': 'Fatih , İstanbul, Turkey', 'suburb...
2     10059872  {'street': 'Hong Kong, Hong Kong Island, Hong ...
3     10084023  {'street': 'Hong Kong , 九龍, Hong Kong', 'subur...
4     10091713  {'street': 'Surry Hills, NSW, Australia', 'sub...
...        ...                                                ...
5550   9985696  {'street': 'Kadıköy, İstanbul, Turkey', 'subur...
5551   9993190  {'street': 'Lahaina, HI, United States', 'subu...
5552   9887054  {'street': 'Hong Kong, Hong Kong Island, Hong ...
5553   9907907  {'street': 'Bondi Beach, NSW, Australia', 'sub...
5554   9936016  {'street': 'Rio de Janeiro, Rio de Janeiro, Br...

[5555 rows x 2 columns]

In [28]:
Host_data= {'_id':[],'street':[],'suburb':[],
              'government_area':[],'market':[],'country':[],
              'country_code':[],'location_type':[], "longitude":[], "latitude":[],
                "is_location_exact":[]}

for i in host_pre["_id"]:
    Host_data["_id"].append(i)

for i in host_pre["address"]:
    Host_data['street'].append(i['street'])
    Host_data['suburb'].append(i["suburb"])
    Host_data['government_area'].append(i["government_area"])
    Host_data['market'].append(i["market"])
    Host_data['country'].append(i["country"])
    Host_data['country_code'].append(i["country_code"])
    
    Host_data['location_type'].append(i["location"]["type"])
    Host_data["longitude"].append(i["location"]["coordinates"][0])
    Host_data["latitude"].append(i["location"]["coordinates"][1])
    Host_data["is_location_exact"].append(i["location"]["is_location_exact"])

In [29]:
Host_data_neighbourhood= pd.DataFrame(Host_data)

In [30]:
Host_data_neighbourhood.head(5)

,_id,street,suburb,government_area,market,country,country_code,location_type,longitude,latitude,is_location_exact
0,1003530,"New York, NY, United States",Manhattan,Upper West Side,New York,United States,US,Point,-73.96523,40.79962,False
1,10133554,"Fatih , İstanbul, Turkey",Fatih,Fatih,Istanbul,Turkey,TR,Point,28.98009,41.00620,False
2,10059872,"Hong Kong, Hong Kong Island, Hong Kong",Central & Western District,Central & Western,Hong Kong,Hong Kong,HK,Point,114.15027,22.28158,True
3,10084023,"Hong Kong , 九龍, Hong Kong",Sham Shui Po District,Sham Shui Po,Hong Kong,Hong Kong,HK,Point,114.16690,22.33140,True
4,10091713,"Surry Hills, NSW, Australia",Darlinghurst,Sydney,Sydney,Australia,AU,Point,151.21554,-33.88029,True

In [31]:
def check_empty_values_improved(df):
    columns_to_check = [
        '_id', 'street', 'suburb', 'government_area', 'market',
        'country', 'country_code', 'location_type', 'longitude',
        'latitude', 'is_location_exact'
    ]
    
    empty_indices = {}
    
    for column in columns_to_check:
        empty_indices[column] = df[df[column] == ''].index.tolist()
    
    # New code to count empty values in each column
    print("Number of empty values in each column:")
    for column, indices in empty_indices.items():
        print(f"{column}: {len(indices)}")

    return empty_indices

In [32]:
empty_indices= check_empty_values_improved(Host_data_neighbourhood)

Number of empty values in each column:
_id: 0
street: 0
suburb: 887
government_area: 0
market: 6
country: 0
country_code: 0
location_type: 0
longitude: 0
latitude: 0
is_location_exact: 0

In [33]:
Host_data_neighbourhood["suburb"]=Host_data_neighbourhood["suburb"].replace({'':"Not Specified"})
Host_data_neighbourhood["market"]=Host_data_neighbourhood["market"].replace({'':"Not Specified"})
#Host_data_neighbourhood["is_location_exact"]=Host_data_neighbourhood["is_location_exact"].map({True:"Yes", False:"No"})

In [34]:
Host_data_neighbourhood # FIANL

,_id,street,suburb,government_area,market,country,country_code,location_type,longitude,latitude,is_location_exact
0,1003530,"New York, NY, United States",Manhattan,Upper West Side,New York,United States,US,Point,-73.965230,40.799620,False
1,10133554,"Fatih , İstanbul, Turkey",Fatih,Fatih,Istanbul,Turkey,TR,Point,28.980090,41.006200,False
2,10059872,"Hong Kong, Hong Kong Island, Hong Kong",Central & Western District,Central & Western,Hong Kong,Hong Kong,HK,Point,114.150270,22.281580,True
3,10084023,"Hong Kong , 九龍, Hong Kong",Sham Shui Po District,Sham Shui Po,Hong Kong,Hong Kong,HK,Point,114.166900,22.331400,True
4,10091713,"Surry Hills, NSW, Australia",Darlinghurst,Sydney,Sydney,Australia,AU,Point,151.215540,-33.880290,True
...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,"Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,29.030790,40.985630,False
5551,9993190,"Lahaina, HI, United States",Lahaina,Lahaina,Maui,United States,US,Point,-156.667520,20.858940,False
5552,9887054,"Hong Kong, Hong Kong Island, Hong Kong",Quarry Bay,Eastern,Hong Kong,Hong Kong,HK,Point,114.207220,22.291570,False
5553,9907907,"Bondi Beach, NSW, Australia",Bondi,Waverley,Sydney,Australia,AU,Point,151.265420,-33.892980,False
5554,9936016,"Rio de Janeiro, Rio de Janeiro, Brazil",Lapa,Centro,Rio De Janeiro,Brazil,BR,Point,-43.173761,-22.908336,False

AVAILABILITY

In [35]:
#AVAILABILITY OF THE HOUSES IN THE NEIGHBOURHOODS

Availability = []

for i in collection.find({},{"_id":1, "availability":1}):
    Availability.append(i)

df_availability= pd.DataFrame(Availability)
df_availability

           _id                                       availability
0      1003530  {'availability_30': 0, 'availability_60': 0, '...
1     10133554  {'availability_30': 30, 'availability_60': 60,...
2     10059872  {'availability_30': 0, 'availability_60': 0, '...
3     10084023  {'availability_30': 14, 'availability_60': 24,...
4     10091713  {'availability_30': 0, 'availability_60': 0, '...
...        ...                                                ...
5550   9985696  {'availability_30': 30, 'availability_60': 60,...
5551   9993190  {'availability_30': 0, 'availability_60': 8, '...
5552   9887054  {'availability_30': 18, 'availability_60': 48,...
5553   9907907  {'availability_30': 0, 'availability_60': 0, '...
5554   9936016  {'availability_30': 0, 'availability_60': 0, '...

[5555 rows x 2 columns]

In [36]:
df_availability_1 = {
    '_id': [],
    'availability_30': [],
    'availability_60': [],
    'availability_90': [],
    'availability_365': []
}

# Populate the '_id' field
df_availability_1['_id'] = df_availability['_id'].tolist()

# Populate the availability fields
# Note the correction from 'availabilty' to 'availability'
for availability in df_availability['availability']:
    df_availability_1['availability_30'].append(availability['availability_30'])
    df_availability_1['availability_60'].append(availability['availability_60'])
    df_availability_1['availability_90'].append(availability['availability_90'])
    df_availability_1['availability_365'].append(availability['availability_365'])

# Create the new DataFrame
Availability_df = pd.DataFrame(df_availability_1)

In [37]:
Availability_df #(FINAL)

,_id,availability_30,availability_60,availability_90,availability_365
0,1003530,0,0,0,93
1,10133554,30,60,90,365
2,10059872,0,0,0,0
3,10084023,14,24,40,220
4,10091713,0,0,0,0
...,...,...,...,...,...
5550,9985696,30,60,90,365
5551,9993190,0,8,31,258
5552,9887054,18,48,78,353
5553,9907907,0,0,0,0
5554,9936016,0,0,0,0

In [38]:
Amenities = []
for i in collection.find({},{"_id":1, "amenities":1}):
    Amenities.append(i)

df_Amenities= pd.DataFrame(Amenities)
df_Amenities

           _id                                          amenities
0      1003530  [Internet, Wifi, Air conditioning, Kitchen, El...
1     10133554  [Internet, Wifi, Air conditioning, Free parkin...
2     10059872  [Air conditioning, Kitchen, Smoking allowed, D...
3     10084023  [TV, Wifi, Air conditioning, Kitchen, Elevator...
4     10091713  [TV, Wifi, Kitchen, Elevator, Heating, Washer,...
...        ...                                                ...
5550   9985696  [TV, Cable TV, Internet, Wifi, Kitchen, Buzzer...
5551   9993190  [TV, Wifi, Air conditioning, Pool, Kitchen, Fr...
5552   9887054  [TV, Wifi, Air conditioning, Kitchen, Elevator...
5553   9907907  [TV, Internet, Wifi, Kitchen, Washer, Dryer, S...
5554   9936016  [TV, Cable TV, Internet, Wifi, Air conditionin...

[5555 rows x 2 columns]

In [39]:
def sort_amenities(x):
    a= x
    a.sort()
    return a


df_Amenities["amenities"]= df_Amenities["amenities"].apply(lambda x: sort_amenities(x))
df_Amenities # DF with sorted amenities(FINAL)

           _id                                          amenities
0      1003530  [Air conditioning, Buzzer/wireless intercom, D...
1     10133554  [Air conditioning, Building staff, Dryer, Esse...
2     10059872  [24-hour check-in, Air conditioning, Doorman, ...
3     10084023  [Air conditioning, Dishes and silverware, Elev...
4     10091713  [Bed linens, Dryer, Elevator, Essentials, Ethe...
...        ...                                                ...
5550   9985696  [Buzzer/wireless intercom, Cable TV, Dryer, Es...
5551   9993190  [Air conditioning, Dryer, Essentials, Family/k...
5552   9887054  [24-hour check-in, Air conditioning, Elevator,...
5553   9907907  [Dryer, Essentials, Hangers, Internet, Kitchen...
5554   9936016  [Air conditioning, Buzzer/wireless intercom, C...

[5555 rows x 2 columns]

JOIN ALL DATA FRAME

In [40]:
df_merged = df_viz.copy()

df_merged = pd.merge(df_merged, df_viz_h, on='_id')
df_merged = pd.merge(df_merged, Host_data_neighbourhood, on='_id')
df_merged = pd.merge(df_merged, Availability_df, on='_id')
df_merged = pd.merge(df_merged, df_Amenities, on='_id')

df_merged

,_id,listing_url,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,...,country_code,location_type,longitude,latitude,is_location_exact,availability_30,availability_60,availability_90,availability_365,amenities
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2,...,US,Point,-73.965230,40.799620,False,0,0,0,93,"[Air conditioning, Buzzer/wireless intercom, D..."
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,Bed and breakfast,Private room,Real Bed,1,1125,moderate,3,...,TR,Point,28.980090,41.006200,False,30,60,90,365,"[Air conditioning, Building staff, Dryer, Esse..."
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient",Apartment,Entire home/apt,Real Bed,4,20,flexible,3,...,HK,Point,114.150270,22.281580,True,0,0,0,0,"[24-hour check-in, Air conditioning, Doorman, ..."
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,Guesthouse,Private room,Futon,1,500,strict_14_with_grace_period,1,...,HK,Point,114.166900,22.331400,True,14,24,40,220,"[Air conditioning, Dishes and silverware, Elev..."
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,Apartment,Entire home/apt,Real Bed,10,21,strict_14_with_grace_period,2,...,AU,Point,151.215540,-33.880290,True,0,0,0,0,"[Bed linens, Dryer, Elevator, Essentials, Ethe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1,1125,flexible,2,...,TR,Point,29.030790,40.985630,False,30,60,90,365,"[Buzzer/wireless intercom, Cable TV, Dryer, Es..."
5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Townhouse,Entire home/apt,Real Bed,3,365,strict_14_with_grace_period,6,...,US,Point,-156.667520,20.858940,False,0,8,31,258,"[Air conditioning, Dryer, Essentials, Family/k..."
5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Apartment,Private room,Real Bed,3,1125,flexible,1,...,HK,Point,114.207220,22.291570,False,18,48,78,353,"[24-hour check-in, Air conditioning, Elevator,..."
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,Apartment,Private room,Real Bed,3,1125,moderate,2,...,AU,Point,151.265420,-33.892980,False,0,0,0,0,"[Dryer, Essentials, Hangers, Internet, Kitchen..."
5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartment,Entire home/apt,Real Bed,1,1125,flexible,6,...,BR,Point,-43.173761,-22.908336,False,0,0,0,0,"[Air conditioning, Buzzer/wireless intercom, C..."

In [41]:
# covert to csv
df_merged.to_csv("Airbnb.csv", index=False)

# save csv file

In [42]:
df_merged.columns

Index(['_id', 'listing_url', 'name', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'price', 'cleaning_fee', 'extra_people', 'guests_included', 'images',
       'review_scores', 'host_id', 'host_url', 'host_name', 'host_location',
       'host_response_time', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_response_rate', 'host_is_superhost',
       'host_has_profile_pic', 'host_identity_verified', 'host_listings_count',
       'host_total_listings_count', 'host_verifications', 'street', 'suburb',
       'government_area', 'market', 'country', 'country_code', 'location_type',
       'longitude', 'latitude', 'is_location_exact', 'availability_30',
       'availability_60', 'availability_90', 'availability_365', 'amenities'],
      dtype='object')

In [2]:
df=pd.read_csv("Airbnb.csv")

In [4]:
df.columns

Index(['_id', 'listing_url', 'name', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'price', 'cleaning_fee', 'extra_people', 'guests_included', 'images',
       'review_scores', 'host_id', 'host_url', 'host_name', 'host_location',
       'host_response_time', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_response_rate', 'host_is_superhost',
       'host_has_profile_pic', 'host_identity_verified', 'host_listings_count',
       'host_total_listings_count', 'host_verifications', 'street', 'suburb',
       'government_area', 'market', 'country', 'country_code', 'location_type',
       'longitude', 'latitude', 'is_location_exact', 'availability_30',
       'availability_60', 'availability_90', 'availability_365', 'amenities'],
      dtype='object')